version: "3.7"

services:
  mysql-service:
    build:
      context: .
      dockerfile: ./docker-config/db/Dockerfile
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - knowienetwork

  spring-service:
    build:
      context: .
      dockerfile: ./docker-config/app/Dockerfile
    env_file:
      - .env
    depends_on:
      - mysql-service
    ports:
      - "${APP_PORT}:8080"
    networks:
      - knowienetwork

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - knowienetwork
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

networks:
  knowienetwork:

volumes:
  database_data: