server:
  error:
    include-stacktrace: on-param
  port: 8080

spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app:
    name: Knowie
    description: "Knowie is an online platform which allows professors to conveniently create, share, administer, and evaluate exams"
    version: 1.1.0
  website: http://knowie.site
  github: https://github.com/gabrielsyphan