server:
  error:
    include-stacktrace: on-param
  port: 8080
spring:
  application:
    name: pweb_project
  datasource:
    url: jdbc:mysql://localhost:3306/pweb_project?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update