server:
  error:
    include-stacktrace: on-param
  port: 8080
spring:
  application:
    name: pweb_project
  datasource:
    url: jdbc:mysql://localhost:3306/knowie?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: ${JWT_SECRET:knowiesecretjwt}