server:
  error:
    include-stacktrace: on-param
  port: 8080
spring:
  application:
    name: pweb_project
  datasource:
    url: jdbc:mysql://localhost:3306/knowie?createDatabaseIfNotExist=true
    username: root
    password: ImTheRoot
  jpa:
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app:
    name: Knowie
    description: "Knowie is an online platform which allows professors to conveniently create, share, administer, and evaluate exams"
    version: 1.1.0
  website: http://knowie.site
  github: https://github.com/gabrielsyphan